api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
        xml: ['application/xml', 'text/xml']
        csv: ['text/csv']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header