doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_pgsql
        types:
            uuid: Symfony\Bridge\Doctrine\Types\UuidType
        replicas:
            replica1:
                url: '%env(resolve:DATABASE_REPLICA_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        quote_strategy: App\Doctrine\SchemaEmulatingQuoteStrategy
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Catalog:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Catalog/Domain/Entity'
                prefix: 'App\Catalog\Domain\Entity'
                alias: Catalog
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'
                alias: User
            Export:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Export/Domain/Entity'
                prefix: 'App\Export\Domain\Entity'
                alias: Export
            Messaging:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Messaging/Domain/Entity'
                prefix: 'App\Messaging\Domain\Entity'
                alias: Messaging
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            driver: pdo_sqlite
            replicas: ~

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system