# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Unix socket — без пароля (локальні системні підключення)
local   all             all                                     trust

# Loopback IPv4/IPv6
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Replication через Unix socket
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

# Дозволяємо реплікацію від replica-контейнера (trust = без пароля всередині Docker-мережі)
host    replication     replicator      all                     trust

# Решта зовнішніх підключень — з паролем
host    all             all             all                     scram-sha-256
